# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

#Vav 1

Pupil.find_or_create_by(first_name: 'יואל', last_name: 'אושרי', class_name: '1')
Pupil.find_or_create_by(first_name: 'אדיר', last_name: 'עדני', class_name: '1')
Pupil.find_or_create_by(first_name: 'דני', last_name: 'חסיד', class_name: '1')
Pupil.find_or_create_by(first_name: 'ניר', last_name: 'שבתאי', class_name: '1')
Pupil.find_or_create_by(first_name: 'לביא', last_name: 'בנגֿֿֿֿֿֿֿֿֿֿֿֿֿ׳ו', class_name: '1')
Pupil.find_or_create_by(first_name: 'אבי', last_name: 'חזן', class_name: '1')
Pupil.find_or_create_by(first_name: 'אדיר', last_name: 'שלום', class_name: '1')
Pupil.find_or_create_by(first_name: 'אמיר', last_name: 'קופולוביץ', class_name: '1')
Pupil.find_or_create_by(first_name: 'ליאור', last_name: 'אבידן', class_name: '1')
Pupil.find_or_create_by(first_name: 'עמי', last_name: 'לובטון', class_name: '1')
Pupil.find_or_create_by(first_name: 'זאב', last_name: 'קסלר', class_name: '1')
Pupil.find_or_create_by(first_name: 'פיני', last_name: 'פרידמן', class_name: '1')

Pupil.find_or_create_by(first_name: 'מור', last_name: 'מזור', class_name: '1')
Pupil.find_or_create_by(first_name: 'ענת', last_name: 'מזרחי', class_name: '1')
Pupil.find_or_create_by(first_name: 'רבקה', last_name: 'קרפלס', class_name: '1')
Pupil.find_or_create_by(first_name: 'סימה', last_name: 'נאון', class_name: '1')
Pupil.find_or_create_by(first_name: 'דורון', last_name: 'בצלאל', class_name: '1')
Pupil.find_or_create_by(first_name: 'ורד', last_name: 'מגדס', class_name: '1')
Pupil.find_or_create_by(first_name: 'אריק', last_name: 'מעודה', class_name: '1')
Pupil.find_or_create_by(first_name: 'שחר', last_name: 'דעוס', class_name: '1')
Pupil.find_or_create_by(first_name: 'יעקב', last_name: 'כהן', class_name: '1')
Pupil.find_or_create_by(first_name: 'ניר', last_name: 'יעקב', class_name: '1')
Pupil.find_or_create_by(first_name: 'ערן', last_name: 'לשם', class_name: '1')
Pupil.find_or_create_by(first_name: 'ציפי', last_name: 'ברנשטין', class_name: '1')
Pupil.find_or_create_by(first_name: 'יהודית', last_name: 'קראווני', class_name: '1')
Pupil.find_or_create_by(first_name: 'שרית', last_name: 'גברא', class_name: '1')
#Pupil.find_or_create_by(first_name: '', last_name: '', class_name: '1')

#Vav 2

Pupil.find_or_create_by(first_name: 'מירב', last_name: 'מחרבי', class_name: '2')
Pupil.find_or_create_by(first_name: 'ענת', last_name: 'גרנות', class_name: '2')
Pupil.find_or_create_by(first_name: 'אורלי', last_name: 'מוזס', class_name: '2')
Pupil.find_or_create_by(first_name: 'סוזי', last_name: 'זכאי', class_name: '2')
Pupil.find_or_create_by(first_name: 'נטע', last_name: 'סדומי', class_name: '2')
Pupil.find_or_create_by(first_name: 'אילת', last_name: 'אבן חן', class_name: '2')
Pupil.find_or_create_by(first_name: 'אביבית', last_name: 'חרד', class_name: '2')
Pupil.find_or_create_by(first_name: 'מירב', last_name: 'דרין', class_name: '2')
Pupil.find_or_create_by(first_name: 'ניר', last_name: 'מחזרי', class_name: '2')
Pupil.find_or_create_by(first_name: 'גבי', last_name: 'נדב', class_name: '2')
Pupil.find_or_create_by(first_name: 'יובל', last_name: 'דויד', class_name: '2')
Pupil.find_or_create_by(first_name: 'דרור', last_name: 'יצחק', class_name: '2')
Pupil.find_or_create_by(first_name: 'אדיר', last_name: 'אפל', class_name: '2')
Pupil.find_or_create_by(first_name: 'משה', last_name: 'קטנוב', class_name: '2')
Pupil.find_or_create_by(first_name: 'טל', last_name: 'שמש', class_name: '2')
Pupil.find_or_create_by(first_name: 'זיו', last_name: 'פרידמן', class_name: '2')
Pupil.find_or_create_by(first_name: 'אלצפן', last_name: 'בוקסבוים', class_name: '2')
Pupil.find_or_create_by(first_name: 'ציון', last_name: 'סרוסי', class_name: '2')
Pupil.find_or_create_by(first_name: 'מני', last_name: 'חדד', class_name: '2')
Pupil.find_or_create_by(first_name: 'אשרת', last_name: 'יצהרי', class_name: '2')
Pupil.find_or_create_by(first_name: 'הילה', last_name: 'איבר', class_name: '2')
Pupil.find_or_create_by(first_name: 'עטרה', last_name: 'קרפלס', class_name: '2')
Pupil.find_or_create_by(first_name: 'רויטל', last_name: 'דרשן', class_name: '2')
Pupil.find_or_create_by(first_name: 'שרית', last_name: 'ביטון', class_name: '2')
Pupil.find_or_create_by(first_name: 'שירית', last_name: 'חדד', class_name: '2')
Pupil.find_or_create_by(first_name: 'סמדר', last_name: '', class_name: '2')
Pupil.find_or_create_by(first_name: 'רונית', last_name: 'פרידלנדר', class_name: '2')
Pupil.find_or_create_by(first_name: 'אורית', last_name: 'שמור', class_name: '2')

#Vav 3

Pupil.find_or_create_by(first_name: 'רחל', last_name: 'אברהם', class_name: '3')
Pupil.find_or_create_by(first_name: 'נתי', last_name: 'אהרוני', class_name: '3')
Pupil.find_or_create_by(first_name: 'שירי', last_name: 'אורזל', class_name: '3')
Pupil.find_or_create_by(first_name: 'שמעון', last_name: 'אנקרי', class_name: '3')
Pupil.find_or_create_by(first_name: 'יוסי', last_name: 'ביטון', class_name: '3')
Pupil.find_or_create_by(first_name: 'עטרה', last_name: 'בן טובים', class_name: '3')
Pupil.find_or_create_by(first_name: 'תמי', last_name: 'הגר', class_name: '3')
Pupil.find_or_create_by(first_name: 'תמר', last_name: 'הלוי', class_name: '3')
Pupil.find_or_create_by(first_name: 'איתן', last_name: 'הרשפלד', class_name: '3')
Pupil.find_or_create_by(first_name: 'תומר', last_name: 'חסיד', class_name: '3')
Pupil.find_or_create_by(first_name: 'טל', last_name: 'כהן', class_name: '3')
Pupil.find_or_create_by(first_name: 'אביטל', last_name: 'לוי', class_name: '3')
Pupil.find_or_create_by(first_name: 'בועז', last_name: 'לוי', class_name: '3')
Pupil.find_or_create_by(first_name: 'יעקב', last_name: 'לנדס', class_name: '3')
Pupil.find_or_create_by(first_name: 'יפית', last_name: 'סולם', class_name: '3')
Pupil.find_or_create_by(first_name: 'יוסי', last_name: 'סאלם', class_name: '3')
Pupil.find_or_create_by(first_name: 'כוכבא', last_name: 'עציוני', class_name: '3')
Pupil.find_or_create_by(first_name: 'כרמית', last_name: 'צאלח', class_name: '3')
Pupil.find_or_create_by(first_name: 'נעמה', last_name: 'שבתאי', class_name: '3')
Pupil.find_or_create_by(first_name: 'טלי', last_name: 'שוקר', class_name: '3')
Pupil.find_or_create_by(first_name: 'יוסי', last_name: 'שוקרון', class_name: '3')
Pupil.find_or_create_by(first_name: 'זהבה', last_name: 'שליסל', class_name: '3')
Pupil.find_or_create_by(first_name: 'אמציה', last_name: 'שינפלד', class_name: '3')
Pupil.find_or_create_by(first_name: 'גלעד', last_name: 'גן', class_name: '3')
Pupil.find_or_create_by(first_name: 'כוכב', last_name: 'נגר', class_name: '3')
